export const APP_WRITE_ID = '6624fe17e44fd02c83ef'
export const DB_ID = 'crm-base'
export const COLLECTION_DEALS = 'deals'
export const COLLECTION_CUSTOMERS = 'customers'
export const COLLECTION_COMMENTS = 'comments'
export const STORAGE_ID = 'storage'
